###################################################################################################
##                                                                                               ##
## Citer - A FUNCTION TO ACQUIRE DOIs OF PAPERS CITING PAPERS IN A VECTOR OF DOIs OF INTEREST ##
##                                                                                               ##
## CREATED BY: MICHAEL FRASER, Ph.D.                                                             ##
## CREATED ON: MARCH 15, 2023                                                                    ##
##                                                                                               ##
###################################################################################################

## Citer is used to scrape opencitations.net to obtain the number of citations for a given list of
## publications. The function takes a vector of digital object identifiers (DOIs), iterates over
## that vector to collect the number of citations for each DOI, and then produces a two-column
## data frame of the original DOI and the number of citations.
##
## Citer is based on on code generated by Stack Overflow user 'anpami', which can be found at:
## https://stackoverflow.com/questions/55064193/retrieve-citations-of-a-journal-paper-using-r
##

citer <- function(doi_vector) { # INPUT IS A VECTOR OF DOIs 
  
  doi_citation_list <- data.frame() # EMPTY DATA FRAME TO HOLD DOIs OF PAPERS CITING EACH PUBLICATION
  doi_citations <- data.frame() # EMPTY DATA FRAME TO HOLD DOIs OF EACH PUBLICATION OF INTEREST
  
  for (i in seq_along(doi_vector)){
    opcit <- paste0("https://opencitations.net/index/coci/api/v1/citations/", doi_vector[[i]]) # CREATE OPENCITATIONS LINK FOR iTH PUBLICATION DOI
    result <- rjson::fromJSON(file = opcit) # DOWNLOAD CITATION DATA IN JSON FORMAT
    citing <- lapply(result, function(x){ # CONVERT JSON RESULT TO R VECTOR
      x[['citing']]
    })
    citing <- unlist(citing)
    citing_length <- n_distinct(citing)
    #citation_vector <- c(doi_vector[[i]], citing_length)
    doi_citation_list <- rbind(doi_citation_list, citing_length) # APPEND CITING DOIs TO DATA FRAME
    doi_citations <- rbind(doi_citations, doi_vector[[i]])
    doi_citations_output <- cbind(doi_citations, doi_citation_list)
    colnames(doi_citations_output) <- c("DOI", "Citation_Number")
  }
  doi_citations_output <- doi_citations_output
}

